### ISSUE TITLE
Add AMD tracing support.

### ISSUE THREAD

**Issue by treshugart** [treshugart/galvatron#8]
We have support for AMD in the globalizer but we need to add a matcher for it.

**Comment by wbinnssmith** [comment]
tada! https://github.com/mrjoelkemp/node-detective-amd

Also from the same author: https://github.com/mrjoelkemp/node-detective-es6

Assuming these have a similar api to `node-detective`, we could standardize the matchers on a similar interface.

**Comment by mrjoelkemp** [comment]
There's also a cleaner abstraction so you don't have to worry about module types: https://github.com/mrjoelkemp/node-precinct. 

Let me know if I can be of any help. Cheers!

**Comment by wbinnssmith** [comment]
Oh wow, this is really awesome. Right now galvatron supports less (the
preprocessor). I wonder if we could make something analogous to the sass
support in detective-sass.

**Comment by mrjoelkemp** [comment]
Totally possible. Open to a PR to add a less-centric detective to precinct.

**Comment by treshugart** [comment]
Thanks for your input @mrjoelkemp! Happy to see there's an abstraction for those. Something that I'm not 100% on is that if detective or precinct will trace. I'm assuming they don't as it seems outside of the scope of the libs as well as something that would require a bit more "opinion" in them. 

To the same tune, we could also provide HTML Import tracing.

**Comment by mrjoelkemp** [comment]
Hi Trey,

For clarification, what do you mean by "trace"?

**Comment by treshugart** [comment]
When it encounters a require attempting to then recursively find
dependencies in that file and that file's dependencies and so forth.

**Comment by mrjoelkemp** [comment]
Thanks for clarifying. No, precinct won't recurse but https://github.com/mrjoelkemp/node-dependency-tree was made for that and uses precinct under the hood.

**Comment by treshugart** [comment]
Interesting. Looking at the code, it seems we could simply replace Galvatron's tracing logic with `node-dependency-tree` for the most part. We'd still need to have the `tracer` service to create file objects from each file, but most of the code could be done away with. This does require the following, though:

- Less support (and eventually HTML Imports support) in `node-precinct` or:
- A way to add "detectives" to `node-precinct`.

I'm a fan of the latter. @mrjoelkemp would you be open to a PR adding the ability to add custom detectives? @wbinnssmith what do you think?

**Comment by wbinnssmith** [comment]
Yeah I like the idea of a pluggable api in precinct, something like

```
var precinct = require('precinct');
var detectiveES6 = require('detective-es6');
var detectiveCJS = require('detective-cjs');

precinct.use(detectiveES6);
precinct.use(detectiveCJS)
```

Where each detective expects to be fed the source text or an ast, and return a list of dependencies (just as they all do now). But there is also some magic going on in `detect-module-type` where I'd guess we'd need to add similar support, and keep that in sync with precinct.

**Comment by mrjoelkemp** [comment]
In general, I'm definitely open to PRs that make the tools useful for other projects. 

I like the idea of a pluggable api.

In the case of LESS, detective-less would likely have to use a regex to grab imports (similar to detective-sass, unless there's a standard AST generator for LESS). 

Your proposed `precinct.use` api could possibly work if it specifies a module type and/or filetypes.

For JS:

```js
precinct.use(detective-es6, 'es6');
precinct.use(detective, 'commonjs');

precinct.use(detective-sass, ['.sass', '.scss']);
precinct.use(detective-less, ['.less']);
```

#### Some background on how precinct works

For abstracting away which detective should be used (specifically for JS), the [`module-definition`](https://github.com/mrjoelkemp/module-definition) module sniffs the ast of the JS file to determine if it's AMD, CJS, or ES6. 

Of course, there's no acorn ast to sniff for a SASS file, so the `precinct.paperwork` endpoint was created as a way to specify a filepath, [sniff the extension](https://github.com/mrjoelkemp/node-precinct/blob/d3dea97c2012d09725813cfaf4b70ff6570b7589/index.js#L74), and pre-specify a module type to the main `precinct` export. [If a type was pre-specified](https://github.com/mrjoelkemp/node-precinct/blob/d3dea97c2012d09725813cfaf4b70ff6570b7589/index.js#L27), then we don't acorn parse the file.

As an alternative to sniffing the extension and using the `paperwork` method, we *could* sniff the content passed to the main `precinct` export for an extension. If it has an extension that's not `.js`, we skip parsing and use the supported detective appropriate for that file extension. I avoided this approach originally because I wanted to avoid a false positive where a file's actual content ended with what could be interpreted as an extension; this is unlikely.
